# environment.yml

name: code-analyzer-env
channels:
  - conda-forge
dependencies:
  - python=3.9
  - flask=2.2.5
  - requests=2.31.0
  - flake8=6.0.0
  - black=23.7.0
  - isort=5.12.0
  - pandas=2.0.3
  - numpy=1.25.0
  - scikit-learn=1.2.2

  # For pip-only packages:
  - pip:
    - bandit==1.7.5
    - coverage==7.2.5
